#!/bin/bash

# https://git.launchpad.net/ubuntu/bionic/+source/vim
# is protected through credentials

/usr/lib/obs/service/corbos_scm \
    --git https://git.launchpad.net/ubuntu/+source/vim \
    --outdir .
